### ISSUE TITLE
Feature - Create Group (Firebase)

### ISSUE THREAD

**Issue by azamatsmith** [azamatsmith/oscars-voting#1]
The user should be able to:
  - Create a new group from the app so that they may share it with their friends

This task will be complete when: 
- [ ]   A firebase project is created and firebase config is added to the app
- [ ]   When a user creates a new group, a new object should be added to firebase
- [ ]   A `group-id` should be created that is easily sharable for a group of voters

**Comment by sethkfman** [comment]
Do we have a Firebase account that I can use or should I just use mine?

**Comment by azamatsmith** [comment]
@sethkfman I haven't opened one, if you could use yours to start with that would be awesome.

**Comment by sethkfman** [comment]
Code for App.js

<script src="https://www.gstatic.com/firebasejs/4.9.1/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "",
    authDomain: "oscars-29f50.firebaseapp.com",
    databaseURL: "https://oscars-29f50.firebaseio.com",
    projectId: "oscars-29f50",
    storageBucket: "",
    messagingSenderId: "695218268092"
  };
  firebase.initializeApp(config);
</script>

**Comment by azamatsmith** [comment]
Sweet, if you could do a PR (once we merge mine) with that code it would be great. We can toss the apiKey in an environment variable. You might be able to use this snippet (`App.js`) as an example.

```
class App extends Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this._onBackPress);
    // make sure not to initialize firebase apps more than once
    if (firebase.apps.length > 0) {
      return;
    }

    const config = {
      apiKey: process.env.API_KEY,
      authDomain: 'io-cabin.firebaseapp.com',
      databaseURL: 'https://io-cabin.firebaseio.com',
      projectId: 'io-cabin',
      storageBucket: 'io-cabin.appspot.com',
      messagingSenderId: '785233942641',
    };
    firebase.initializeApp(config);
    firebase.auth().onAuthStateChanged(user => {
      const action = {
        type: 'UPDATE_USER',
        user,
      };
      store.dispatch(action);
    });
  }
```

**Comment by sethkfman** [comment]
@azamatsmith @brooksmarka  @joshbadger  Database structure below for groups and users. Let me know what you think and I will add structure to firebase.
<img width="245" alt="screen shot 2018-02-10 at 11 20 02 am" src="https://user-images.githubusercontent.com/10342624/36065181-66d2129a-0e54-11e8-9594-b3a76d31d07b.png">

**Comment by sethkfman** [comment]
@azamatsmith @joshbadger @brooksmarka  
All, I have added the above structure into firebase and set the authentication to null. We should be able to add groups and users
