### ISSUE TITLE
Question - Find a free api for movie data

### ISSUE THREAD

**Issue by azamatsmith** [azamatsmith/oscars-voting#2]
Possibly: 
  - http://www.omdbapi.com/

**Comment by sethkfman** [comment]
https://opendata.stackexchange.com/questions/3668/is-there-an-api-for-the-oscars-academy-awards-that-lists-past-winners-as-well-as

**Comment by azamatsmith** [comment]
That is awesome @sethkfman! I downloaded the excel file that someone created. We'll still need to use the omdb site to pull in pictures of the movies etc. 
[Oscars.xlsx](https://github.com/azamatsmith/oscars-voting/files/1701445/Oscars.xlsx)

**Comment by azamatsmith** [comment]
Closing. We are going to use OMDB along with the spreadsheet that @sethkfman found.
