### ISSUE TITLE
Feature - Add Navigation 

### ISSUE THREAD

**Issue by azamatsmith** [azamatsmith/oscars-voting#4]
We'll use [React Navigation](https://reactnavigation.org/) as our navigation library.

**Comment by sethkfman** [comment]
I am just going to jump in here and see if I can make some head way. If you have any comments let me know.

**Comment by azamatsmith** [comment]
@sethkfman Crud, I completely missed your message. I just whipped it up since it gets pretty hairy with Redux and I've fought that battle before.
